joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 1.57
    has_jerk_limits: true
    max_jerk: 0.785

  joint_2:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 1.57
    has_jerk_limits: true
    max_jerk: 0.785

  joint_3:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 1.57
    has_jerk_limits: true
    max_jerk: 0.785

  joint_4:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 1.57
    has_jerk_limits: true
    max_jerk: 0.785

  joint_5:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 1.57
    has_jerk_limits: true
    max_jerk: 0.785

  joint_6:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 1.57
    has_jerk_limits: true
    max_jerk: 0.785
