bridges:
  - ros_topic_name: "joint_states"
    gz_topic_name: "/world/default/model/mobile_robot_with_arm/joint_state"
    ros_type_name: "sensor_msgs/msg/JointState"
    gz_type_name: "gz.msgs.Model"
    direction: GZ_TO_ROS

  - ros_topic_name: "scan"
    gz_topic_name: "/world/default/model/mobile_robot_with_arm/sensor/lidar_link/scan"
    ros_type_name: "sensor_msgs/msg/LaserScan"
    gz_type_name: "gz.msgs.LaserScan"
    direction: GZ_TO_ROS

  - ros_topic_name: "camera/image_raw"
    gz_topic_name: "/world/default/model/mobile_robot_with_arm/sensor/camera_optical_frame/image"
    ros_type_name: "sensor_msgs/msg/Image"
    gz_type_name: "gz.msgs.Image"
    direction: GZ_TO_ROS
